{% set name = "persistent" %}
{% set version = "6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/persistent-{{ version }}.tar.gz
  sha256: 01d94668b54d3d5fbab9eb41d81f41e3d8407a7233fd2a928a6417e4dc11d429

build:
  number: 0
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - zope.interface
    - cffi
    - pycparser
  run:
    - python
    - zope.interface
    - cffi
    - zope.deferredimport

test:
  imports:
    - persistent
    - persistent._timestamp
    - persistent.cPersistence
    - persistent.cPickleCache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/persistent/
  license: BSD-3-Clause AND ZPL-2.1
  license_family: Other
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt
  summary: Translucent persistent objects
  description: |
    Persistent contains a generic persistence implementation for Python. It
    forms the core protocol for making objects interact "transparently" with
    a database such as the ZODB.
  doc_url: https://persistent.readthedocs.io
  dev_url: https://github.com/zopefoundation/persistent/
