{% set name = "persistent" %}
{% set version = "6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01d94668b54d3d5fbab9eb41d81f41e3d8407a7233fd2a928a6417e4dc11d429

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
    - cffi
    - zope
    - zope.interface
    - zope.deferredimport
  run:
    - python
    - cffi
    - zope
    - zope.interface
    - zope.deferredimport

test:
  imports:
    - persistent
    - persistent._timestamp
    - persistent.cPersistence
    - persistent.cPickleCache
  requires:
    - pip
    - pytest
    - manuel
  commands:
    - pip check
    # AssertionError: could not find my setup.py
    - pytest -v --pyargs persistent.tests -k "not test_suite"

about:
  home: https://github.com/zopefoundation/persistent
  license: BSD-3-Clause AND ZPL-2.1
  license_family: Other
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt
  summary: Translucent persistent objects
  description: |
    Persistent contains a generic persistence implementation for Python. It
    forms the core protocol for making objects interact "transparently" with
    a database such as the ZODB.
  doc_url: https://persistent.readthedocs.io
  dev_url: https://github.com/zopefoundation/persistent
